%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Written by I. Michaelis (GFZ), 2019
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
conf_panel_bfield=struct(...
'range',struct(...
    'bfield_L',[-20:1:-2 2:1:20], ...%[2,4,4.5], ...
    'bfield_Lon',0, ...%[-175:-5:0 5:5:180], ...%-180:5:180 ...%-180:30:180 ...
    'plot_xlim',[-15 15], ...
    'plot_ylim',[-15 10], ...
    'plot_zlim',[-10 10] ...
), ...
'color',struct(...
    'esl','y', ...
    'sat','w', ...
    'sat_text','w', ...
    'bfield','blue' ...%[234 239 191]./255, ...
), ...
'scale',struct(...
    'esl_x',[20 1], ...
    'esl_y',[0 0], ...
    'esl_z',[0 0], ...
    'esl',1.2, ...
    'esl_text',10, ...
    'cam_zoom',3, ...
    'sat',8, ...
    'sat_text',10, ...
    'sat_text_scale',20 ...
), ...
'view',struct(...
    'bfield',[135 17] ...%[135 40] ...%[200 165] ...
), ...
'pos',struct(...
    'text_esl',[15,0,1], ...
    'bfield_sat',[0.1300    0.5374    0.3347    0.3876] ...
) ...
);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
conf_panel_donut_scatter=struct(...
'range',struct(...
    'bfield_L',[-20:1:-2 2:1:20], ...%[2,4,4.5], ...
    'bfield_Lon',0, ...%[-175:-5:0 5:5:180], ...%-180:5:180 ...%-180:30:180 ...
    'donut_xyz',[[0 8];[0 8];[0 6]], ...
    'flux_donut',[-0.5 3.0], ...
    'donut_parts',5:8 ...
), ...
'scale',struct(...
    'cam_zoom',1.5, ...
    'sat',8, ...
    'sat_text',10, ...
    'sat_text_scale',20, ...
    'flux_donut_colorbar',12, ...
    'donut_alpha',.2, ...
    'donut_xyz_res',[.2,.2,.2], ...
    'donut_sph_res',[.1,5,5], ...
    'donut_marker','o', ...
    'donut_point',25, ...
    'donut_point_rescale',0 ...
), ...
'color',struct(...
    'sat','w', ...
    'sat_text','w' ...
), ...
'view',struct(...
    'donut',[142 20] ...
), ...
'pos',struct(...
    'flux_donut',[0.1300    0.1100    0.3347    0.3876], ...
    'flux_donut_colorbar',[0.15 0.05 0.3 0.0264] ...%[0.2212 0.1901 0.1521 0.0264] ...
) ...
);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
conf_panel_data=struct(...
'range',struct(...
    'L',[1 7.5], ...
    'L_ticks',[3 5 7], ...
    'flux',[0.5 4.0] ...
), ...
'scale',struct(...
    'act_lwd',2, ...
    'flux_rawdata',10, ...
    'flux_yaxis',12, ...
    'flux_colorbar',8, ...
    'frame_width',1 ...
), ...
'color',struct(...
    'utc','white', ...%'utc',[0.93 0.69 0.19], ...%'yellow'
    'axes','white', ...
    'act','red', ...
    'cmap',jet(256) ...
), ...
'view',struct(...
), ...
'pos',struct(...
    'colbar',[0.88    0.6927    0.0176    0.22], ...
    'data',[0.5703    0.6799    0.3347    0.2451] ...
) ...
);
% conf_panel_data.color.cmap(1,:)=[0 0 0];
% conf_panel_data.color.cmap(1,:)=[0 1 1];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
conf_panel_sim=struct(...
'range',struct(...
    'L',[1 7.5], ...
    'L_ticks',[3 5 7], ...
    'flux',[0.5 4.0] ...
), ...
'scale',struct(...
    'act_lwd',2, ...
    'flux_rawdata',10, ...
    'flux_yaxis',12, ...
    'flux_colorbar',8, ...
    'frame_width',1 ...
), ...
'color',struct(...
    'utc','white', ...%'utc',[0.93 0.69 0.19], ...%'yellow'
    'axes','white', ...
    'act','red', ...
    'cmap',jet(256) ...
), ...
'view',struct(...
), ...
'pos',struct(...
    'sim',[0.5703    0.3950    0.3347    0.2451] ...
) ...
);
conf_panel_sim.color.cmap(1,:)=[0 0 0];
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
conf_panel_sw=struct(...
'range',struct(...
    'swn',[0 80], ...
    'swn_ticks',[0 40 80], ...
    'swv',[300 850], ...
    'swv_ticks',[300 500 700] ...
), ...
'scale',struct(...
    'act_lwd',2, ...
    'sw_yaxis',12, ...
    'sw_sz',14, ...
    'frame_width',1 ...
), ...
'color',struct(...
    'swn',[0.150   0.675,  0.902], ...%'blue'
    'swv',[1 0.55 0.26], ...%'orangered'
    'utc','white', ...%'utc',[0.93 0.69 0.19], ...%'yellow'
    'axes','white', ...
    'act','red' ...
), ...
'view',struct(...
), ...
'pos',struct(...
    'sw',[0.5703    0.2500    0.3347    0.122] ...
) ...
);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
conf_panel_kp=struct(...
'range',struct(...
    'kp',[0 9] ...
), ...
'scale',struct(...
    'kp_yaxis',12, ...
    'act_lwd',2, ...
    'frame_width',1 ...
), ...
'color',struct(...
    'act','red', ...
    'kp','green', ...
    'utc','white', ...%'utc',[0.93 0.69 0.19], ...%'yellow'
    'axes','white' ...
), ...
'view',struct(...
), ...
'pos',struct(...
    'kp',[0.5703    0.100    0.3347    0.122] ...
) ...
);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
conf_panel_title=struct(...
'range',struct(...
), ...
'scale',struct(...
    'title',16 ...
), ...
'color',struct(...
    'title','yellow' ...
), ...
'view',struct(...
), ...
'pos',struct(...
    'title',[0.1300 0.1100 0.8250 0.8550] ...
) ...
);
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

